const data = [
  {
    name: "virat kohli",
    employeeId: "gads01",
    type: "new employee",
    progress: "1/5",
    status: "In-Progress",
    startDate: "10/06/18",
    unit: "uroll oy",
    hiring: "rehan",
  },
  {
    name: "ms dhoni",
    employeeId: "gads02",
    type: "new employee",
    progress: "1/3",
    status: "In-Progress",
    startDate: "12/03/15",
    unit: "uroll oy",
    hiring: "devon lane",
  },
  {
    name: "md siraj",
    employeeId: "gads03",
    type: "new employee",
    progress: "1/5",
    status: "In-Progress",
    startDate: "19/03/19",
    unit: "uroll oy",
    hiring: "asad khan",
  },
  {
    name: "rohit sharma",
    employeeId: "gads04",
    type: "new employee",
    progress: "1/7",
    status: "In-Progress",
    startDate: "06/03/16",
    unit: "uroll oy",
    hiring: "kane peter",
  },
  {
    name: "kl rahul",
    employeeId: "gads05",
    type: "new employee",
    progress: "1/5",
    status: "In-Progress",
    startDate: "12/03/20",
    unit: "uroll oy",
    hiring: "arun chawla",
  },
  {
    name: "jadeja",
    employeeId: "gads06",
    type: "new employee",
    progress: "1/6",
    status: "In-Progress",
    startDate: "09/03/14",
    unit: "uroll oy",
    hiring: "devon conway",
  },
  {
    name: "bumrah",
    employeeId: "gads07",
    type: "new employee",
    progress: "1/8",
    status: "In-Progress",
    startDate: "08/03/19",
    unit: "uroll oy",
    hiring: "stark",
  },
  {
    name: "md sami",
    employeeId: "gads08",
    type: "new employee",
    progress: "1/5",
    status: "In-Progress",
    startDate: "23/03/14",
    unit: "uroll oy",
    hiring: "devon lane",
  },
  {
    name: "sunil kumar",
    employeeId: "gads09",
    type: "new employee",
    progress: "1/2",
    status: "In-Progress",
    startDate: "16/04/18",
    unit: "uroll oy",
    hiring: "bravo",
  },
  {
    name: "sachin",
    employeeId: "gads10",
    type: "new employee",
    progress: "1/5",
    status: "In-Progress",
    startDate: "07/09/13",
    unit: "uroll oy",
    hiring: "kapil",
  },
];

export default data